/// <reference types="Cypress" />

describe('Teste funcional', () => {
    before(() =>{
        cy.visit('https://bugbank.netlify.app/')
    })

    it('Criar cadastro e efetuar login',() =>{
        cy.get('.ihdmxA').click()
        cy.get(':nth-child(2) > .input__default')
            .type('teste@gmail.com')
        cy.get(':nth-child(3) > .input__default')
            .type('teste')
        cy.get(':nth-child(4) > .style__ContainerFieldInput-sc-s3e9ea-0 > .input__default')
            .type('123')
        cy.get(':nth-child(5) > .style__ContainerFieldInput-sc-s3e9ea-0 > .input__default')
            .type('123')
        cy.get('.styles__ContainerFormRegister-sc-7fhc7g-0 > .style__ContainerButton-sc-1wsixal-0').click()
        cy.get('#modalText').should('contain','foi criada com sucesso')
        cy.get('#btnCloseModal').click()
        cy.get('.style__ContainerFormLogin-sc-1wbjw6k-0 > :nth-child(1) > .input__default').type('teste@gmail.com')
        cy.get('.style__ContainerFormLogin-sc-1wbjw6k-0 > .login__password > .style__ContainerFieldInput-sc-s3e9ea-0 > .input__default').type('123')  
        cy.get('.otUnI')
        .click()
        cy.get('#textName').should('have.text','Olá teste,')
    })
    it('Validar campos usuário logado',() =>{
        cy.get('.home__InitialLetterName-sc-1auj767-5').should('exist')
        cy.get(':nth-child(1) > .home__TransactionText-sc-1auj767-10').should('have.text','TRANSFERÊNCIA')
        cy.get(':nth-child(2) > .home__TransactionText-sc-1auj767-10').should('have.text','PAGAMENTOS')
        cy.get(':nth-child(3) > .home__TransactionText-sc-1auj767-10').should('have.text','EXTRATO')
        cy.get(':nth-child(4) > .home__TransactionText-sc-1auj767-10').should('have.text','SAQUE')
        cy.get('.home__Footer-sc-1auj767-16 > .home__Text-sc-1auj767-9').should('exist')
        cy.get('.home__ContainerLink-sc-1auj767-2').should('exist')
        cy.get('[src="/_next/image?url=%2Fimgs%2Ftransfer.png&w=128&q=75"]').click()
        cy.get('.transfer__TextInformation-sc-1yjpf2r-7').should('have.text','Realize transferência de valores entre contas BugBank com taxa 0 e em poucos segundos.')
        cy.get('#btnBack').click()
        cy.get('#btn-PAGAMENTOS').click()
        cy.get('#btn-PAGAMENTOS').should('exist')
        cy.get('#modalText').contains('em desenvolvimento')
        cy.get('#btnCloseModal').click()
        cy.get('#btn-EXTRATO').click()
        cy.get('.bank-statement__LabelText-sc-7n8vh8-10').should('have.text','Saldo disponível')
        cy.get('#btnBack').click()
        cy.get('#btn-SAQUE').click()
        cy.get('.styles__ContainerContent-sc-8zteav-1').should('exist')
        cy.get('#modalText').contains('em desenvolvimento')
        cy.get('#btnCloseModal').click()
        cy.get('.home__ContainerLink-sc-1auj767-2').click()
    })    
  
})    